<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddBillingColumnsToFeeMastersTable extends Migration
{
    public function up()
    {
        Schema::table('fee_masters', function (Blueprint $table) {
            if (!Schema::hasColumn('fee_masters', 'billing_run_id')) {
                $table->unsignedInteger('billing_run_id')->nullable()->after('status');
                $table->foreign('billing_run_id')
                    ->references('id')->on('fee_billing_runs')
                    ->onDelete('set null');
            }
            if (!Schema::hasColumn('fee_masters', 'billing_period_key')) {
                // Stored for fast duplicate-check: "2026-06", "2026-Q2", etc.
                $table->string('billing_period_key', 20)->nullable()->after('billing_run_id');
                $table->index('billing_period_key', 'idx_fee_masters_period_key');
            }
            if (!Schema::hasColumn('fee_masters', 'source_type')) {
                // 'manual' = existing workflow; 'recurring' = auto-generated by billing profile
                $table->enum('source_type', ['manual', 'recurring'])->default('manual')->after('billing_period_key');
            }
        });
    }

    public function down()
    {
        Schema::table('fee_masters', function (Blueprint $table) {
            if (Schema::hasColumn('fee_masters', 'billing_run_id')) {
                $table->dropForeign(['billing_run_id']);
                $table->dropColumn('billing_run_id');
            }
            if (Schema::hasColumn('fee_masters', 'billing_period_key')) {
                $table->dropIndex('idx_fee_masters_period_key');
                $table->dropColumn('billing_period_key');
            }
            if (Schema::hasColumn('fee_masters', 'source_type')) {
                $table->dropColumn('source_type');
            }
        });
    }
}
