<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Student ID Verification - Lalmai Govt. College</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, Helvetica, sans-serif; background: #eef2f6; min-height: 100vh;
               display: flex; align-items: center; justify-content: center; padding: 16px; }
        .card { background: #fff; border-radius: 12px; box-shadow: 0 4px 18px rgba(0,0,0,.12);
                max-width: 380px; width: 100%; overflow: hidden; text-align: center; }
        .head { background: #e01e26; color: #fff; padding: 14px 10px; }
        .head .cname { font-size: 18px; font-weight: 900; }
        .head .sub { font-size: 12px; font-weight: bold; opacity: .95; }
        .body { padding: 18px 16px 22px 16px; }
        .photo { width: 110px; height: 132px; object-fit: cover; border: 3px solid #e01e26;
                 border-radius: 8px; background: #eee; }
        .status { display: inline-block; margin-top: 10px; padding: 4px 18px; border-radius: 14px;
                  font-weight: 900; font-size: 13px; color: #fff; }
        .ok { background: #1d9b48; }
        .bad { background: #c0392b; }
        table { margin: 14px auto 0 auto; font-size: 14px; text-align: left; }
        td { padding: 3px 6px; }
        td.lb { font-weight: bold; white-space: nowrap; }
        .invalid { padding: 30px 14px; }
        .invalid .x { font-size: 46px; }
        .foot { font-size: 11px; color: #777; padding: 0 12px 16px 12px; }
    </style>
</head>
<body>
    <div class="card">
        <div class="head">
            <div class="cname">Lalmai Govt. College</div>
            <div class="sub">Cumilla Sadar South, Cumilla &mdash; Student ID Verification</div>
        </div>
        @if(isset($student) && $student)
            @php
                $name = strtoupper(trim(preg_replace('/\s+/', ' ', $student->first_name.' '.$student->middle_name.' '.$student->last_name)));
                $photo = $student->student_image
                    ? asset('images/studentProfile/'.$student->student_image)
                    : asset('assets/images/avatars/profile-pic.jpg');
                $active = strtolower((string) $student->status) === 'active';
            @endphp
            <div class="body">
                <img class="photo" src="{{ $photo }}" alt="">
                <br>
                <span class="status {{ $active ? 'ok' : 'bad' }}">{{ $active ? 'VALID - ACTIVE STUDENT' : 'NOT ACTIVE' }}</span>
                <table>
                    <tr><td class="lb">Name</td><td>:</td><td>{{ $name }}</td></tr>
                    <tr><td class="lb">Roll No</td><td>:</td><td>{{ $student->reg_no }}</td></tr>
                    @if($student->faculty_name)
                        <tr><td class="lb">Group</td><td>:</td><td>{{ strtoupper($student->faculty_name) }}</td></tr>
                    @endif
                    @if($student->batch_title)
                        <tr><td class="lb">Session</td><td>:</td><td>{{ $student->batch_title }}</td></tr>
                    @endif
                    @if($student->blood_group)
                        <tr><td class="lb">Blood Group</td><td>:</td><td>{{ $student->blood_group }}</td></tr>
                    @endif
                </table>
            </div>
        @else
            <div class="invalid">
                <div class="x">&#10060;</div>
                <h3>Invalid ID Card</h3>
                <p style="margin-top:6px;color:#666;">This QR code does not match any student record.<br>Please contact the college office.</p>
            </div>
        @endif
        <div class="foot">This page is generated by Lalmai Govt. College IMS. Scan result at {{ date('d M Y, h:i A') }}.</div>
    </div>
</body>
</html>
